Repository runway-reviews/runway-reviews-fe, pull requests merged in 2024-02, with the labels that each got.

#1 feat/add circle ci, start building vue app
  ci.circleci/config.yml
Labels: enhancement

#2 feat/Add components for skeleton of app, add animation, styling for h…
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/base.css
  src/assets/logo.svg
  src/assets/main.css
  src/assets/runway.json
  src/assets/styles.css
  src/components/AddReview.vue
  src/components/AirportDetailsPage.vue
  src/components/AirportDropdown.vue
  src/components/Header.vue
  src/components/Login.vue
  src/components/__tests__/HelloWorld.cy.js
  src/main.js
Labels: enhancement

#9 bug/Fix deployment issues
  package-lock.json
Labels: bug

#16 feat/Add routing to login and add review buttons
  src/App.vue
  src/components/AirportDropdown.vue
  src/router/index.js
  src/views/AddReview.vue
  src/views/AirportDetailsPage.vue
  src/views/Login.vue
Labels: bug, enhancement

#18 Feature/styling/zm
  src/components/AirportDropdown.vue
  src/router/index.js
  src/views/AddReview.vue
  src/views/AirportDetailsPage.vue
Labels: enhancement

#19 feat/Add background image and button styling
  public/leonardo-yip-rn-NLirHQPY-unsplash (3).jpg
  src/App.vue
  src/assets/styles.css
  src/views/AddReview.vue
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: styling

#23 Feature/login functionality/ep
  package-lock.json
  package.json
  src/App.vue
  src/components/Login.vue
  src/main.js
  src/router/index.js
  src/views/Home.vue
Labels: enhancement

#24 bug-fix/Fix merge conflict
  src/assets/styles.css
  src/components/Login.vue
  src/views/Login.vue
Labels: bug fix

#26 feat/Remove add-review routing, fix style accordingly, fix close butt…
  src/components/Login.vue
  src/views/AddReview.vue
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: enhancement

#28 fix/Login display
  src/assets/styles.css
  src/components/Login.vue
  src/views/AddReview.vue
  src/views/Home.vue
Labels: bug fix

#29 feat/Pass current user as a prop down to airport details page for add…
  src/components/AirportDropdown.vue
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: enhancement

#30 Feature/current user passdown/ep
  src/components/AirportDropdown.vue
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: enhancement

#31 fix/Add url to vue config file
  .gitignore
  dist/assets/index-eZcdFfMc.css
  dist/assets/index-p34NHYGa.js
  dist/favicon.ico
  dist/index.html
  dist/leonardo-yip-rn-NLirHQPY-unsplash (3).jpg
  vite.config.js
  vue.config.js
Labels: bug fix

#36 Feature/fix routing and styling/ep
  index.html
  package-lock.json
  package.json
  public/add.png
  public/home.png
  public/user.png
  src/assets/styles.css
  src/components/AirportDropdown.vue
  src/components/Login.vue
  src/main.js
  src/views/AddReview.vue
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: styling

#44 feat/Create user history across webpages
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: bug fix

#46 Feature/carousel ep
  dist/index.html
  package-lock.json
  package.json
  public/Screenshot 2024-02-27 at 4.07.11 PM.png
  public/annie-spratt-qyAka7W5uMY-unsplash.jpg
  public/arthur-edelmans-u9QuzlImpzA-unsplash.jpg
  public/artur-tumasjan-KZSNMN4VxR8-unsplash.jpg
  public/caroline-selfors-r2jpr8MDw0I-unsplash.jpg
  public/dewang-gupta-ESEnXckWlLY-unsplash.jpg
  public/jeshoots-com-mSESwdMZr-A-unsplash.jpg
  public/josue-isai-ramos-figueroa-n2NBgIx3A28-unsplash.jpg
  public/nick-fewings-l5fDJ3I-9Uk-unsplash.jpg
  src/assets/styles.css
  src/components/AirportDropdown.vue
  src/components/CarouselImages.vue
  src/main.js
  src/views/AirportDetailsPage.vue
  src/views/Home.vue
Labels: enhancement
